# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifier_rdv.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modifier_rdv(object):
    def setupUi(self, modifier_rdv):
        modifier_rdv.setObjectName("modifier_rdv")
        modifier_rdv.resize(488, 313)
        self.centralwidget = QtWidgets.QWidget(modifier_rdv)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.tableWidget_anc = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget_anc.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_anc.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_anc.setObjectName("tableWidget_anc")
        self.tableWidget_anc.setColumnCount(8)
        self.tableWidget_anc.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_anc.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_anc.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_anc.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_anc.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_anc.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_anc.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_anc.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_anc.setHorizontalHeaderItem(7, item)
        self.gridLayout_2.addWidget(self.tableWidget_anc, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_3)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_2.addWidget(self.dateTimeEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        modifier_rdv.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(modifier_rdv)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 488, 18))
        self.menubar.setObjectName("menubar")
        modifier_rdv.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(modifier_rdv)
        self.statusbar.setObjectName("statusbar")
        modifier_rdv.setStatusBar(self.statusbar)

        self.retranslateUi(modifier_rdv)
        QtCore.QMetaObject.connectSlotsByName(modifier_rdv)

    def retranslateUi(self, modifier_rdv):
        _translate = QtCore.QCoreApplication.translate
        modifier_rdv.setWindowTitle(_translate("modifier_rdv", "MainWindow"))
        self.label.setText(_translate("modifier_rdv", "Selectionner le RDV pour modifier la date"))
        item = self.tableWidget_anc.horizontalHeaderItem(0)
        item.setText(_translate("modifier_rdv", "num"))
        item = self.tableWidget_anc.horizontalHeaderItem(1)
        item.setText(_translate("modifier_rdv", "file"))
        item = self.tableWidget_anc.horizontalHeaderItem(2)
        item.setText(_translate("modifier_rdv", "item"))
        item = self.tableWidget_anc.horizontalHeaderItem(3)
        item.setText(_translate("modifier_rdv", "capacite"))
        item = self.tableWidget_anc.horizontalHeaderItem(4)
        item.setText(_translate("modifier_rdv", "weight"))
        item = self.tableWidget_anc.horizontalHeaderItem(5)
        item.setText(_translate("modifier_rdv", "instance"))
        item = self.tableWidget_anc.horizontalHeaderItem(6)
        item.setText(_translate("modifier_rdv", "bincount"))
        item = self.tableWidget_anc.horizontalHeaderItem(7)
        item.setText(_translate("modifier_rdv", "execution"))
        self.label_2.setText(_translate("modifier_rdv", "Date/heure"))
        self.pushButton.setText(_translate("modifier_rdv", "Modifier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modifier_rdv = QtWidgets.QMainWindow()
    ui = Ui_modifier_rdv()
    ui.setupUi(modifier_rdv)
    modifier_rdv.show()
    sys.exit(app.exec_())
